# Generated by Django 6.1 on 2026-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
