# Generated by Django 6.1 on 2026-09-03 05:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_subcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
