# Generated by Django 6.1 on 2026-09-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
